---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  labels:
    app: mongo-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: mongo-data-pv
#spec:
#  accessModes:
#    - ReadWriteOnce
#  capacity:
#    storage: 1Gi
#  hostPath:
#    path: /data/mongo
---