apiVersion: apps/v1
kind: Deployment
metadata:
  name: notepad
  labels:
    app: notepad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notepad
  template:
    metadata:
      labels:
        app: notepad
      annotations:
        prometheus.io/port: "2112"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: notepad
          image: davidkornel/notepad-demo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          command:
            - /notepad
          args:
            - "--mongo-uri=mongodb://mongo.default.svc:27017"
            - "--monitoring-port=2112"